config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/index'
  post 'cards/import'

  resources :cards do
    member {get :destroy}
  end

  resources :students do
    collection { post :import }
    collection { get :report }
    member {get :details}
  end
  resources :students

  resources :checkins

  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  
  resources :events do
    member do
      get :check
      post :checkin
      post :checkback
    end
  end

  resources :users, :except => ['new', 'create']
  

  get 'pages/home'
  get 'pages/help'

  devise_for :admins

  root 'pages#home'

  get "*path" => redirect("/")
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates_presence_of :fname, :lname, :email
	validates_length_of :uin, :is => 9, :allow_blank => true
	validates_format_of :fname, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
	validates_format_of :lname, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
	
	has_many :checkins, :dependent => :destroy
	has_many :events, through: :checkins
	
	filterrific :default_filter_params => { :sorted_by => 'fname_asc' },
              :available_filters => %w[
                sorted_by
                search_query
                with_uin
                with_fname
                with_lname
                with_term
                with_year
              ]
	self.per_page = 10
	

	scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.to_s.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 5
    where(
      terms.map {
        or_clauses = [
          "LOWER(students.uin) LIKE ?",
          "LOWER(students.fname) LIKE ?",
          "LOWER(students.lname) LIKE ?",
          "LOWER(students.email) LIKE ?",
          "LOWER(students.year) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }
    

    scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
	    when /^uin_/
	      order("LOWER(students.uin) #{ direction }")
	    when /^fname_/
	      order("LOWER(students.fname) #{ direction }")
      when /^lname_/
        order("LOWER(students.lname) #{ direction }")
	    when /^email/
	      order("LOWER(students.email) #{ direction }")
      when /^term_/
        order("LOWER(students.term) #{ direction }")
      when /^year/
        order("LOWER(students.year) #{ direction }")
	    else
	      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end

  }

  def self.options_for_sorted_by
    [
      ['uin (0-9)', 'uin_asc'],
      ['uin (9-0)', 'uin_desc'],
      ['First Name (a-z)', 'fname_asc'],
      ['First Name (z-a)', 'fname_desc'],
      ['Last Name (a-z)', 'lname_asc'],
      ['Last Name (z-a)', 'lname_desc'],
      ['Term (a-z)', 'term_asc'],
      ['Term (z-a)', 'term_desc'],
      ['Year (0-9)', 'year_asc'],
      ['Year (9-0)', 'year_desc']
    ]
  end
  
  scope :with_uin, lambda { |uin|
    where(:uin => [*uin])
  }

  scope :with_fname, lambda { |fname|
    where(:fname => [*fname])
  }

  scope :with_lname, lambda { |lname|
    where(:lname => [*lname])
  }

  scope :with_term, lambda { |term|
    where(:term => [*term])
  }

  scope :with_year, lambda { |year|
    where(:year => [*year])
  }
  def self.options_for_uin_select
    Student.uniq.pluck(:uin)
  end

  def self.options_for_fname_select
    Student.uniq.pluck(:fname)
  end

  def self.options_for_lname_select
    Student.uniq.pluck(:lname)
  end
  
  def self.options_for_term_select
    Student.uniq.pluck(:term)
  end

  def self.options_for_year_select
    Student.uniq.pluck(:year)
  end


	def self.import(file)
  	  	CSV.foreach(file.path, headers: true) do |row|
      		Student.create! row.to_hash
    	end
	end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
    csv << column_names
    all.each do |checkin|
      csv << checkin.attributes.values_at(*column_names)
    end
  end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /students
  # GET /students.json
  def index
    if admin_signed_in?
      @filterrific = initialize_filterrific(
        Student,
        params[:filterrific],
        :select_options => {
          sorted_by: Student.options_for_sorted_by,
          with_uin: Student.options_for_uin_select,
          with_fname: Student.options_for_fname_select,
          with_lname: Student.options_for_lname_select,
          with_term: Student.options_for_term_select,
          with_year: Student.options_for_year_select
        }
      ) or return
       @students = @filterrific.find.page(params[:page])
    end
    respond_to do |format|
      format.html
      format.js
    end 
  end

  # GET /students/1/details
  def details
    @checkins = Checkin.where(student_id: @student.id).order(:created_at).reverse_order.paginate(:page => params[:page])
    @student = Student.find(@student.id)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def import
    begin
       Student.import(params[:file])
       redirect_to students_url, notice: "Students imported."
    rescue
       redirect_to students_url, notice: "Error in imported file!"
    end
  end

  def report
    if admin_signed_in?
      @filterrific = initialize_filterrific(
        Student,
        params[:filterrific],
        :select_options => {
          sorted_by: Student.options_for_sorted_by,
          with_uin: Student.options_for_uin_select,
          with_fname: Student.options_for_fname_select,
          with_lname: Student.options_for_lname_select,
          with_term: Student.options_for_term_select,
          with_year: Student.options_for_year_select
        }
      ) or return
       @students = @filterrific.find.page(params[:page])
    end
    respond_to do |format|
      format.html
      format.js
      format.csv { 
        @students = @students.paginate(:page => params[:page], :per_page => @students.count)
        render text: @students.to_csv }
      format.xls { 
        @students = @students.paginate(:page => params[:page], :per_page => @students.count)
        send_data @students.to_csv(col_sep: "\t") }
    end 
  end
  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:uin, :fname, :lname, :email, :term, :year)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fname, label: false, placeholder: 'First Name', required: true %>
    <%= f.input :lname, label: false, placeholder: 'Last Name', required: true %>
    <%= f.input :email, label: false, placeholder: 'Email', required: true %>
    <%= f.input :uin, label: false, placeholder: 'UIN', required: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/_list.html.erb
  <%= page_entries_info @students, :model => 'student' =%>
  <br></br>

  <p id="notice"><%= notice %></p>

  <%if !@students.empty? %>
  <table>
    <thead>
      <tr>
        <th>UIN</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Term</th>
        <th>Year</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <% end %>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.uin %></td>
          <td><%= student.fname %></td>
          <td><%= student.lname %></td>
          <td><%= student.email %></td>
          <td><%= student.term %></td>
          <td><%= student.year %></td>
          <td><%= link_to 'Show', student %></td>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/students/_listreport.html.erb
<%= page_entries_info @students, :model => 'student' =%>

<br></br>
<table>
  <thead>
    <% if !@students.empty? %>
      <tr>
        <th>UIN</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Department Events</th>
        <th>Industrial Events</th>
        <th>Term</th>
        <th>Year</th>
        <th>Details</th>
      </tr>
    <% end %>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.uin %></td>
        <td><%= student.fname %></td>
        <td><%= student.lname %></td>
        <td><%= student.email %></td>
        <td><%= student.deptevents %></td>
        <td><%= student.indevents %></td>
        <td><%= student.term %></td>
        <td><%= student.year %></td>
        <td><%= link_to 'Details', details_student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/details.html.erb
<%= page_entries_info @checkins, :model => 'checkin' =%>
 <p id="notice"><%= notice %></p>

 <div style="display:inline-block;">
  <table>
    <tr>
      <td>
        <strong>First Name:</strong>
          <%= @student.fname %>
      </td>
      <td>
        <strong>Last Name:</strong>
          <%= @student.lname %>
      </td>
      <td>
        <strong>UIN:</strong>
          <%= @student.uin %>
      </td>
      <td>
        <strong>Email:</strong>
          <%= @student.email %>
      </td>
    </tr>
  </table>
</div>
<br> </br>

<%if !@checkins.empty? %>
  <table>
      <thead>
        <tr>
          <th>Event</th>
          <th>Term</th>
          <th>Date</th>
          <th>Location</th>
          <th>Time</th>
          <th>Check-in Time</th>
          <% if admin_signed_in? %>
            <th colspan = 2>Manage</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @checkins.each do |checkin| %>
          <tr>
            <td><%= checkin.event.name %></td>
            <td><%= checkin.event.term %></td>
            <td><%= checkin.event.date %></td>
            <td><%= checkin.event.location %></td>
            <td><%= checkin.event.time %></td>
            <td><%= l checkin.created_at, format: "%I:%M %p" %></td>
            <% if admin_signed_in? %>
            <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
            <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/students/edit.html.erb
<h3>Editing Student</h3>

<%= render 'form' %>

<br> </br>
<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

 <div class="form-group" >
  <%= form_tag import_students_path, multipart: true do %>
 <div class="input-group">
    <%= file_field_tag :file %>
    <span class="input-group-btn">
       <%= submit_tag("Import", :class => "sub_button" ) %>
    </span>
 </div>
 <% end %>
</div>

<hr>

<h3>Listing Students</h3>
<%= form_for_filterrific @filterrific do |f| =%>
      <tr>
        <td>
          <%= f.text_field :search_query, :class => 'filterrific-periodically-observed form-control' =%>
        </td>
        <td>
          <%= f.select :sorted_by, @filterrific.select_options[:sorted_by],
                      {}, { :class => 'form-control' } =%>
        </td>
        <td>
          <%= link_to "Reset filters", reset_filterrific_url =%>
        </td>
        <td>
          <%= link_to 'New Student', new_student_path %>
        </td>
        <td>
          <%= render_filterrific_spinner =%>
        </td>
      </tr>
  <% end %>
<br>
<div id="results">
  <%= render :partial => 'students/list',
           :locals => { :students => @students } =%>
</div>
  <br>
  <p><%= will_paginate @students =%></p>
  <br>

app/views/students/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'students/list',
    :locals => { :students => @students }
  )
) %>
$("#results").html("<%= js %>");

app/views/students/new.html.erb
<h3>New Student</h3>

<%= render 'form' %>

<br> </br>
<%= link_to 'Back', students_path %>

app/views/students/report.html.erb
<p id="notice"><%= notice %></p>

<h3>Student Report</h3>
<%= form_for_filterrific @filterrific do |f| =%>
      <tr>
        <td>
          <%= f.text_field :search_query, :class => 'filterrific-periodically-observed form-control' =%>
        </td>
        <td>
          <%= f.select :sorted_by, @filterrific.select_options[:sorted_by],
                      {}, { :class => 'form-control' } =%>
        </td>
        <td>
          <%= link_to "Reset filters", reset_filterrific_url =%> <%= render_filterrific_spinner =%>
        </td>
        <td>
          <%= link_to "Download", "/students/report.xls", :format => 'xls' %>
        </td>
      </tr>
  <% end %>
<br>
<div id="results">
  <%= render :partial => 'students/listreport',
           :locals => { :students => @students } =%>
</div>
  <br>
  <p><%= will_paginate @students =%></p>
  <br>

app/views/students/report.js.erb
<% js = escape_javascript(
  render(
    :partial => 'students/listreport',
    :locals => { :students => @students }
  )
) %>
$("#results").html("<%= js %>");

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uin:</strong>
  <%= @student.uin %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @student.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @student.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<br> </br>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>