config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/index'
  post 'cards/import'

  resources :cards do
    member {get :destroy}
  end

  resources :students do
    collection { post :import }
    collection { get :report }
    member {get :details}
  end
  resources :students

  resources :checkins

  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  
  resources :events do
    member do
      get :check
      post :checkin
      post :checkback
    end
  end

  resources :users, :except => ['new', 'create']
  

  get 'pages/home'
  get 'pages/help'

  devise_for :admins

  root 'pages#home'

  get "*path" => redirect("/")
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name, :kind
  has_many :checkins, :dependent => :destroy
  has_many :students, through: :checkins

	filterrific :default_filter_params => { :sorted_by => 'date_asc' },
              :available_filters => %w[
                sorted_by
                search_query
                with_term
                with_year
              ]
	self.per_page = 10

	scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.to_s.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
      terms.map {
        or_clauses = [
          "LOWER(events.name) LIKE ?",
          "LOWER(events.location) LIKE ?",
          "LOWER(events.typename) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
	    when /^name_/
	      order("LOWER(events.name) #{ direction }")
	    when /^location_/
	      order("LOWER(events.location) #{ direction }")
      when /^date_/
        order("events.date #{ direction }")
	    when /^term/
	      order("LOWER(events.term) #{ direction }")
	    else
	      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Name (z-a)', 'name_desc'],
      ['Location (a-z)', 'location_asc'],
      ['Location (z-a)', 'location_desc'],
      ['Term (a-z)', 'term_asc'],
      ['Term (z-a)', 'term_desc']
    ]
  end

  scope :with_term, lambda { |term|
    where(:term => [*term])
  }

  scope :with_year, lambda { |year|
    where(:year => [*year])
  }

  def self.options_for_year_select
    Event.uniq.pluck(:year)
  end

  def self.options_for_term_select
    Event.uniq.pluck(:term)
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
    csv << column_names
    all.each do |checkin|
      csv << checkin.attributes.values_at(*column_names)
    end
  end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def check
     @checkins = Checkin.where(event_id: @event.id).order(:created_at).reverse_order
  end

  def checkin
    if Card.exists?(:number => params["card"])
      @checkstudent = Student.find_by(uin: Card.find_by(number: params["card"]).uin)
      if(@checkstudent)
        if Checkin.exists?(:event_id => @event.id, :student_id => @checkstudent.id)
          flash.now[:notice] = 'Student already checked in for this event!'
        else
          @cin = Checkin.create(:event_id => @event.id, :student_id => @checkstudent.id)
      	  if(@event.kind == "Department")
      		  @checkstudent.deptevents += 1
      	  else
      		  @checkstudent.indevents += 1
      	  end
      	  @checkstudent.save
          @cin.save
        end
      else
    	  flash.now[:notice] = 'Student data not available! Please contact the administrator!'
      end
    else
      flash.now[:notice] = 'Card data not found! Please enter!'
      @render_student = true
      @card = params["card"]
    end

    @checkins = Checkin.where(event_id: @event.id).order(:created_at).reverse_order
    respond_to do |format|
      format.js
    end
  end

  def checkback
    if Student.exists?(:uin => params["uin"])
      @cardstu = Card.create(:number => params["card"],:uin => params["uin"])
      @cardstu.save
      @checkstudent = Student.find_by(uin: params["uin"])
      @chin = Checkin.create(:event_id => @event.id, :student_id => Student.find_by(uin: @cardstu.uin).id)
      if(@event.kind == "Department")
        @checkstudent.deptevents += 1
      else
        @checkstudent.indevents += 1
      end

      if @chin.save and @checkstudent.save
        flash.now[:notice] = 'Student record created and checked in!'
      end
    else
      if(params["uin"].size != 9)
        flash.now[:notice] = 'UIN must be 9 digits long!'
      else
        flash.now[:notice] = 'UIN not found! Please contact the administrator!'
      end
    end  

    @checkins = Checkin.where(event_id: @event.id).order(:created_at).reverse_order
    respond_to do |format|
        format.js
    end
  end

  # GET /events
  # GET /events.json
  def index
    if admin_signed_in?
      @filterrific = initialize_filterrific(
        Event,
        params[:filterrific],
        :select_options => {
          sorted_by: Event.options_for_sorted_by,
          with_term: Event.options_for_term_select,
          with_year: Event.options_for_year_select
        }
      ) or return
      @events = @filterrific.find.page(params[:page])
    elsif user_signed_in?
      @events = Event.where(date: Date.today).paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html
      format.js
      format.csv { 
        @events = @events.paginate(:page => params[:page], :per_page => @events.count)
        render text: @events.to_csv }
      format.xls { 
        @events = @events.paginate(:page => params[:page], :per_page => @events.count)
        send_data @events.to_csv(col_sep: "\t") }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :year, :term, :date, :location, :time, :kind, :typename)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_checklist.html.erb
<p id="notice"><%= notice %></p>
<table>
    <thead>
      <%if !@checkins.empty? %>
        <tr>
          <th>Student First Name</th>
          <th>Last Name</th>
          <th>Check-in Time</th>
        </tr>
      <% else %>
      <tr> <a>This event has no check-in history! </a></tr>
      <% end %>
    </thead>

    <tbody>
      <% @checkins.each do |checkin| %>
        <tr>
          <td><%= checkin.student.fname %></td>
          <td><%= checkin.student.lname %></td>
          <td><%= l checkin.created_at, format: "%I:%M %p" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Back', events_path %>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: 'Name', label: false %>
    <%= f.input :year, collection: 2015..2020, label: false %>
    <%= f.input :term, collection: ["Spring", "Summer", "Fall", "Winter"], label: false %>
    <%= f.input :date, as: :date_picker, label: false, placeholder: 'Date' %>
    <%= f.input :location, label: false, placeholder: 'Location' %>
    <%= f.input :time, as: :time_picker, label: false, placeholder: 'Time' %>
    <%= f.input :kind, collection: ["Department", "Industrial"], label: false %>
    <%= f.input :typename, label: false, placeholder: 'Department/Industry Name' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/_list.html.erb
  <%= page_entries_info @events, :model => 'event' =%>

  <p id="notice"><%= notice %></p>

  <%if !@events.empty? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Year</th>
        <th>Term</th>
        <th>Date</th>
        <th>Location</th>
        <th>Time</th>
        <th colspan="3">Manage</th>
      </tr>
    </thead>
  <% end %>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.year %></td>
          <td><%= event.term %></td>
          <td><%= l event.date, format: :short %></td>
          <td><%= event.location %></td>
          <td><%= event.time %></td>
          <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if admin_signed_in? or user_signed_in? %>
          <td><%= link_to 'Check-in', check_event_path(event) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/events/_studentform.html.erb
<%= form_tag "/events/#{@event.id}/checkback.js", :id => 'checkback', remote: true do %>
  <%= text_field_tag "uin", nil, :label => false, :placeholder => 'UIN' %>
  <%= text_field_tag "card", @card, :label => false, :placeholder => 'Card Number' %>
  <br></br>
         <%= submit_tag 'Check in' %>
<% end %>

app/views/events/check.html.erb
<p id="notice"><%= notice %></p>

<div style="display:inline-block;">
  <table>
    <tr>
      <td>
        <strong>Event:</strong>
          <%= @event.name %>
      </td>
      <td>
        <strong>Term:</strong>
          <%= @event.term %> <%= @event.year %>
      </td>
      <td>
        <strong>Date:</strong>
          <%= @event.date %>
      </td>
      <td>
        <strong>Location:</strong>
          <%= @event.location %>
      </td>
      <td>
        <strong>Time:</strong>
          <%= @event.time %>
      </td>
    </tr>
  </table>
</div>
<br> </br>

<%= form_tag "/events/#{@event.id}/checkin", :id => 'swipe', remote: true do %>
  <h4><a>Swipe:</a>&nbsp;&nbsp;<%= text_field_tag "card" %> 
  <%= check_box_tag "fast" %> <a>Fast</a> </h4>
<% end %>

<br> </br>

<div id="fill_student", style="display:inline-block;">
</div>

<br> </br>
<div id="check_list", style="display:inline-block;">
  <%= render :partial => 'events/checklist',
           :locals => { :checkins => @checkins } =%>
</div>

app/views/events/checkback.js.erb
$("#checkback").remove()

<% jsw = escape_javascript(
  render(
    :partial => 'events/checklist',
    :locals => { :checkins => @checkins }
  )
) %>

$("#check_list").html("<%= jsw %>");
$("#card").val("")
$('#card').focus()

app/views/events/checkin.js.erb
<% js = escape_javascript(
  render(
    :partial => 'events/checklist',
    :locals => { :checkins => @checkins }
  )
) %>

<% if @render_student %>
	$("#fill_student").html("<%= j render(:partial => 'events/studentform', :locals => { :card => @card }) %>");
<% end %>

$("#check_list").html("<%= js %>");
$("#card").val("")
$('#card').focus()

app/views/events/edit.html.erb
<h3>Editing Event</h3>

<%= render 'form' %>
<br>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if admin_signed_in? %>
  <h3>Listing Events</h3>
  <%= form_for_filterrific @filterrific do |f| =%>
      <tr>
        <td>
          <%= f.text_field :search_query, :class => 'filterrific-periodically-observed form-control' =%>
        </td>
        <td>
          <%= f.select :with_term, @filterrific.select_options[:with_term],
                     { :include_blank => '- Term -' },
                     { :class => 'form-control' } =%>
        </td>
        <td>
          <%= f.select :with_year, @filterrific.select_options[:with_year],
                     { :include_blank => '- Year -' },
                     { :class => 'form-control' } =%>
        </td>
        <td>
          <%= f.select :sorted_by, @filterrific.select_options[:sorted_by],
                      {}, { :class => 'form-control' } =%>
        </td>
      </tr>
  <% end %>
  <br>
  <tr>
    <td>
      <%= link_to "Reset filters", reset_filterrific_url =%>
    </td>
    <td>
      <%= render_filterrific_spinner =%>
    </td>
    <td>
      <%= link_to "Download List", "/events.xls", :format => 'xls' %>
    </td>
  </tr>
<br></br>
<% elsif user_signed_in? %>
<h2>Today's Events</h2>
<% end %>
<div id="results">
  <%= render :partial => 'events/list',
           :locals => { :events => @events } =%>
</div>
  <p><%= will_paginate @events =%></p>
  <br>
  <% if admin_signed_in? %>
  <%= link_to 'New Event', new_event_path %>
  <% end %>

app/views/events/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'events/list',
    :locals => { :events => @events }
  )
) %>
$("#results").html("<%= js %>");

app/views/events/new.html.erb
<h3>New Event</h3>

<%= render 'form' %>

<br> </br>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @event.year %>
</p>

<p>
  <strong>Term:</strong>
  <%= @event.term %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<br> </br>

<% if admin_signed_in? %>
<%= link_to 'Edit', edit_event_path(@event) %> | 
<% end %>
<%= link_to 'Back', events_path %>