config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/index'
  post 'cards/import'

  resources :cards do
    member {get :destroy}
  end

  resources :students do
    collection { post :import }
    collection { get :report }
    member {get :details}
  end
  resources :students

  resources :checkins

  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  
  resources :events do
    member do
      get :check
      post :checkin
      post :checkback
    end
  end

  resources :users, :except => ['new', 'create']
  

  get 'pages/home'
  get 'pages/help'

  devise_for :admins

  root 'pages#home'

  get "*path" => redirect("/")
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
	belongs_to :student
	belongs_to :event

	self.per_page = 10

	filterrific :available_filters => %w[
                sorted_by
                search_query
              ]
    scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 6
    where(
      terms.map {
        or_clauses = [
          "LOWER(checkins.event.name) LIKE ?",
          "LOWER(checkins.event.term) LIKE ?",
          "LOWER(checkins.event.location) LIKE ?",
          "LOWER(checkins.student.fname) LIKE ?",
          "LOWER(checkins.student.lname) LIKE ?",
          "LOWER(checkins.student.uin) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
	    when /^name_/
	      order("LOWER(checkins.event.name) #{ direction }")
	    when /^location_/
	      order("LOWER(checkins.event.location) #{ direction }")
      when /^date_/
        order("checkins.event.date #{ direction }")
	    when /^term/
	      order("LOWER(checkins.event.term) #{ direction }")
	    else
	      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Name (z-a)', 'name_desc'],
      ['Location (a-z)', 'location_asc'],
      ['Location (z-a)', 'location_desc'],
      ['Term (a-z)', 'term_asc'],
      ['Term (z-a)', 'term_desc']
    ]
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
    csv << column_names
    all.each do |checkin|
      csv << checkin.attributes.values_at(*column_names)
    end
  end
end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /checkins
  # GET /checkins.json

  def index
    @filterrific = initialize_filterrific(
      Checkin,
      params[:filterrific],
      :select_options => {
        sorted_by: Checkin.options_for_sorted_by
      }
    ) or return
    @checkins = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
      format.csv { 
        @checkins = @checkins.paginate(:page => params[:page], :per_page => @checkins.count)
        render text: @checkins.to_csv }
      format.xls { 
        @checkins = @checkins.paginate(:page => params[:page], :per_page => @checkins.count)
        send_data @checkins.to_csv(col_sep: "\t") }
    end
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Checkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:event_id, :student_id)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= simple_form_for(@checkin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :event_id, label: false, placeholder: 'Event ID' %>
    <%= f.input :student_id, label: false, placeholder: 'Student ID' %>
    <%= f.input :created_at, label: false, placeholder: 'Created At' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checkins/_list.html.erb
<%= page_entries_info @checkins, :model => 'checkin' =%>
 <p id="notice"><%= notice %></p>
<table>
    <thead>
      <tr>
        <th>Event</th>
        <th>Term</th>
        <th>Date</th>
        <th>Location</th>
        <th>Time</th>
        <th>Student First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>UIN</th>
        <th>Check-in Time</th>
        <% if admin_signed_in? %>
          <th colspan = 2>Manage</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @checkins.each do |checkin| %>
        <tr>
          <td><%= checkin.event.name %></td>
          <td><%= checkin.event.term %></td>
          <td><%= checkin.event.date %></td>
          <td><%= checkin.event.location %></td>
          <td><%= checkin.event.time %></td>
          <td><%= checkin.student.fname %></td>
          <td><%= checkin.student.lname %></td>
          <td><%= checkin.student.email %></td>
          <td><%= checkin.student.uin %></td>
          <td><%= l checkin.created_at, format: "%I:%M %p" %></td>
          <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
          <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/checkins/edit.html.erb
<h3>Editing Checkin</h3>

<%= render 'form' %>

<br>
<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<h3>Listing Checkins</h3>
  <%= form_for_filterrific @filterrific do |f| =%>
      <tr>
        <td>
          <%= f.text_field :search_query, :class => 'filterrific-periodically-observed form-control' =%>
        </td>
        <td>
          <%= f.select :sorted_by, @filterrific.select_options[:sorted_by],
                      {}, { :class => 'form-control' } =%>
        </td>
        <td>
          <%= link_to "Reset filters", reset_filterrific_url =%>
        </td>
        <td>
          <%= link_to "Download", "/checkins.xls", :format => 'xls' %>
        </td>
  <% end %>
<%= render_filterrific_spinner =%>
<br>
<div id="results">
  <%= render :partial => 'checkins/list',
           :locals => { :checkins => @checkins } =%>
</div>
  <p><%= will_paginate @checkins =%></p>
  <br>
  <% if admin_signed_in? %>
  <%= link_to 'New Checkin', new_checkin_path %>
  <% end %>

app/views/checkins/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'checkins/list',
    :locals => { :checkins => @checkins }
  )
) %>
$("#results").html("<%= js %>");

app/views/checkins/new.html.erb
<h3>New Checkin</h3>

<%= render 'form' %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>