config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/index'
  post 'cards/import'

  resources :cards do
    member {get :destroy}
  end

  resources :students do
    collection { post :import }
    collection { get :report }
    member {get :details}
  end
  resources :students

  resources :checkins

  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  
  resources :events do
    member do
      get :check
      post :checkin
      post :checkback
    end
  end

  resources :users, :except => ['new', 'create']
  

  get 'pages/home'
  get 'pages/help'

  devise_for :admins

  root 'pages#home'

  get "*path" => redirect("/")
end

app/views/layouts/application.html.erb
<% title = "Seminar Management System" %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= title =%></title>
      <%= favicon_link_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <%= yield :head %>
    </head>
  <body>
    <div id="menu-wrapper" style="text-align: center; padding: 15px;">
      <div style="display: inline-block;"><h1 id="menu-head">Student Engineers' Council, Texas A&M University</h1></div>
      <br>
      <div style="display: inline-block;"><a id="menu-head">Seminar Management System</a></div>
    </div>

    <ul id="menu-menu">
      <li><a href='/'><span>Home</span></a></li>

      <% if admin_signed_in? %>
        <li><a href=<%= events_path =%>><span>Events</span></a></li>
        <li><a href=<%= students_path  =%>><span>Students</span></a></li>
        <li><a href=<%= cards_index_path  =%>><span>Cards</span></a></li>
      <% end %>
      <% if admin_signed_in? %>
        <li><a href='/users'><span>Staff</span></a></li>
        <li><a href=<%= checkins_path  =%>><span>Check-ins</span></a></li>
        <li><a href=<%= report_students_path =%>><span>Reports</span></a></li>
        <li class="menu-last" ><%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <li class="menu-right" ><a>Logged in as: <%= current_admin.username %></a></li>
      <% elsif user_signed_in? %>
        <li class="menu-nobar" ><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <li class="menu-right" ><a>Logged in as: <%= current_user.username %></a></li>
      <% else %>
        <li class="menu-nobar" ><%= link_to "Staff Login", new_user_session_path, :class => 'navbar-link' %></li>
        <li class="menu-last" ><%= link_to "Admin Login", new_admin_session_path, :class => 'navbar-link' %></li>
      <% end %>

      <li><a href='/pages/help'><span>Help</span></a></li>
    </ul>

    <div><%= alert=%></div>
    <div style="text-align:center"><div style="display:inline-block;"><%= yield %></div></div>

    <div style="text-align: center; padding: 15px;">    
  <div id="footer" style="display: inline-block;"><p style="color: #fff;"><%= l Time.zone.now, format: "%e %b, %I:%M %p" =%></p></div>
  </div>
  </body>
</html>